<a href="https://colab.research.google.com/github/GrayWrld7/testrepo/blob/master/PY0101EN_5_2_Numpy2D_edited.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# 2D Numpy in Python

Estimated time needed: **20** minutes

## Objectives

After completing this lab you will be able to:

*   Operate comfortably with `numpy`
*   Perform complex operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-thttps://op/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01: 20px">
    <ul>
        <li><a href="https://create/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Create a 2D Numpy Array</a></li>
        <li><a href="https://access/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Accessing different elements of a Numpy Array</a></li>
        <li><a href="op">Basic Operations</a></li>
    </ul>

</div>

<hr>


<h2 id="create">Create a 2D Numpy Array</h2>


In [ ]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
X=np.array([[1,0,1],[2,2,2]])

In [ ]:
X

array([[1, 0, 1],
       [2, 2, 2]])

In [ ]:
out=X[0:2,2]
out

array([1, 2])

In [ ]:
out2=X[0,0:2]
out2

array([1, 0])

In [63]:
X1=np.array([[1,0],[0,1]])
Y1=np.array([[2,2],[2,2]])
Z1=np.dot(X1,Y1)
Z1

array([[2, 2],
       [2, 2]])

In [62]:
X2=np.array([[1,2],[3,4]])
Y2=np.array([[5,6],[7,8]])
Z2=np.dot(X2,Y2)
Z2

array([[19, 22],
       [43, 50]])

In [ ]:
X2*Y2

array([[ 5, 12],
       [21, 32]])

In [49]:
X3=np.array([[1,2,3],[4,5,6]])
Y3=np.array([[7,8,9],[10,11,12]])
#Z3=np.dot(X3,Y3)
print(X3)
print(Y3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [13]:
X3

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
Y3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
print("X3 ndim:", X3.ndim)
print("Y3 ndim:", Y3.ndim)
print("X3 shape:", X3.shape)
print("Y3 shape:", Y3.shape)
print("X3 size:", X3.size)
print("Y3 size:", Y3.size)

X3 ndim: 2
Y3 ndim: 2
X3 shape: (2, 3)
Y3 shape: (2, 3)
X3 size: 6
Y3 size: 6


In [26]:
print("Hadamard product:\n", X3*Y3,"\n")
print("Addition:\n", X3+Y3,"\n")
print("Subtraction:\n", X3-Y3)

Hadamard product:
 [[ 7 16 27]
 [40 55 72]] 

Addition:
 [[ 8 10 12]
 [14 16 18]] 

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]


In [39]:
Y3copy = Y3[:]
Y3copy

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
Y3[0,0]=100
print("First index, first element of Y3 changed to:", Y3[0,0])
print(Y3)

First index, first element of Y3 changed to: 100
[[100   8   9]
 [ 10  11  12]]


In [53]:
print("Y3 original:\n", Y3,"\n")
print("Y3[0,0] original before change:", Y3[0,0],"\n\n")
print("Y3copy:\n", Y3copy,"\n")
print("Y3copy[0,0] before change:", Y3copy[0,0])
Y3copy[0,0]=200
print("Y3copy[0,0] after change:", Y3copy[0,0],"\n")
print("Y3copy after change:\n", Y3copy,"\n\n")
print("Y3[0,0] after change:", Y3[0,0],"\n")
print("Y3 original after change:\n", Y3,"\n")

Y3 original:
 [[ 7  8  9]
 [10 11 12]] 

Y3[0,0] original before change: 7 


Y3copy:
 [[500   8   9]
 [ 10  11  12]] 

Y3copy[0,0] before change: 500
Y3copy[0,0] after change: 200 

Y3copy after change:
 [[200   8   9]
 [ 10  11  12]] 


Y3[0,0] after change: 7 

Y3 original after change:
 [[ 7  8  9]
 [10 11 12]] 



In [54]:
Y3[0,0]=350
print("Y3[0,0]:", Y3[0,0])
print("Original Y3:\n", Y3,"\n\n")
print("Y3copy[0,0]", Y3copy[0,0],"\n")
print("Y3copy:\n", Y3copy)

Y3[0,0]: 350
Original Y3:
 [[350   8   9]
 [ 10  11  12]] 


Y3copy[0,0] 200 

Y3copy:
 [[200   8   9]
 [ 10  11  12]]


In [55]:
print("Y3copy[0,1] before change:", Y3copy[0,1],"\n")
print("Y3[0,1] original before change:", Y3[0,1],"\n")
Y3copy[0,1]=900
print("Y3copy[0,1] after change:", Y3copy[0,1],"\n")
print("Y3copy after change:\n", Y3copy,"\n\n")
print("Y3[0,1] original after change:", Y3[0,1],"\n")
print("Y3 orignal after change:\n", Y3)


Y3copy[0,1] before change: 8 

Y3[0,1] original before change: 8 

Y3copy[0,1] after change: 900 

Y3copy after change:
 [[200 900   9]
 [ 10  11  12]] 


Y3[0,1] original after change: 8 

Y3 orignal after change:
 [[350   8   9]
 [ 10  11  12]]


In [56]:
Y3.T

array([[350,  10],
       [  8,  11],
       [  9,  12]])

In [59]:
Y3

array([[350,   8,   9],
       [ 10,  11,  12]])

In [76]:
Y3[0,0]=7
Y3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [80]:
Y3T=Y3.T
Y3T

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [88]:
X3T=X3.T
X3T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
def dotProduct(a,b):
 return np.dot(a,b)

In [92]:
dotProduct(X3,Y3T)

array([[ 50,  68],
       [122, 167]])

In [110]:
print("Y3T is the transponed version of Y3\n")
print("New 'ndim' of matrix multiplication/dot between X3 and Y3T:", dotProduct(X3,Y3T).ndim)
print("New 'size' of matrix multiplication/dot between X3 and Y3T:", dotProduct(X3,Y3T).size)
print("New 'shape' of matrix multiplication between X3 and Y3T:", dotProduct(X3,Y3T).shape)

Y3T is the transponed version of Y3

New 'ndim' of matrix multiplication/dot between X3 and Y3T: 2
New 'size' of matrix multiplication/dot between X3 and Y3T: 4
New 'shape' of matrix multiplication between X3 and Y3T: (2, 2)


In [101]:
dotProduct(X3T,Y3)

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [111]:
print("Note: X3T is the transponed version of X3\n")
print("New 'ndim' of matrix multiplication/dot between X3T and Y3:", dotProduct(X3T,Y3).ndim)
print("New 'size' of matrix multiplication/dot between X3T and Y3:", dotProduct(X3T,Y3).size)
print("New 'shape' of matrix multiplication between X3T and Y3:", dotProduct(X3T,Y3).shape)

Note: X3T is the transponed version of X3

New 'ndim' of matrix multiplication/dot between X3T and Y3: 2
New 'size' of matrix multiplication/dot between X3T and Y3: 9
New 'shape' of matrix multiplication between X3T and Y3: (3, 3)


In [109]:
X4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("X4 numpy array:\n", X4,"\n")
print("X4 ndim:", X4.ndim)
print("X4 size:", X4.size)
print("X4 shape:", X4.shape)

X4 numpy array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

X4 ndim: 2
X4 size: 9
X4 shape: (3, 3)


In [112]:
Y4=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Y4 numpy array:\n", Y4,"\n")
print("Y4 ndim:", Y4.ndim)
print("Y4 size:", Y4.size)
print("Y4 shape:", Y4.shape)

Y4 numpy array:
 [[10 11 12]
 [13 14 15]
 [16 17 18]] 

Y4 ndim: 2
Y4 size: 9
Y4 shape: (3, 3)


In [115]:
Z4=dotProduct(X4,Y4)
Z4

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [116]:
print("Z4 numpy array:\n", Z4,"\n")
print("Z4 ndim:", Z4.ndim)
print("Z4 size:", Z4.size)
print("Z4 shape:", Z4.shape)

Z4 numpy array:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]] 

Z4 ndim: 2
Z4 size: 9
Z4 shape: (3, 3)


In [143]:
print("sine (Sinus) applied to Z4:\n")
np.sin(Z4)

sine (Sinus) applied to Z4:



array([[ 0.73319032,  0.89399666,  0.98358775],
       [-0.06189025,  0.69605849, -0.99568419],
       [-0.64356121,  0.42013968,  0.99999007]])

Consider the list <code>a</code>, which contains three nested lists **each of equal size**.


In [58]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a Numpy Array as follows:


In [114]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank.


In [117]:
# Show the numpy array dimensions

A.ndim

2

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [118]:
# Show the numpy array shape

A.shape

(3, 3)

The total number of elements in the array is given by the attribute <code>size</code>.


In [119]:
# Show the numpy array size

A.size

9

<hr>


<h2 id="access">Accessing different elements of a Numpy Array</h2>


We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500" />


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400" />


We simply use the square brackets and the indices corresponding to the element we would like:


In [120]:
# Access the element on the second row and third column

A[1, 2]

23

We can also use the following notation to obtain the elements:


In [121]:
# Access the element on the second row and third column

A[1][2]

23

Consider the elements shown in the following figure


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400" />


We can access the element as follows:


In [122]:
# Access the element on the first row and first column

A[0][0]

11

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400" />


This can be done with the following syntax:


In [123]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [124]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Corresponding to the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


<h2 id="op">Basic Operations</h2>


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500" />


The numpy array is given by <code>X</code> and <code>Y</code>


In [125]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [126]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

We can add the numpy arrays as follows.


In [127]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500" />


We can perform the same operation in numpy as follows


In [128]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [129]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500" />


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [130]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [131]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [132]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [133]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [135]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function <code>dot</code> to multiply the arrays together.


In [136]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [137]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [144]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [145]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array.


In [150]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [154]:
A=np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [159]:
# Write your code below and press Shift+Enter to execute
print("A.Size:", A.size)
print("A.shape:", A.shape)
print("A.ndim:", A.ndim)

A.Size: 12
A.shape: (3, 4)
A.ndim: 2


<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [160]:
# Write your code below and press Shift+Enter to execute
A[0,0:2]

array([1, 2])

<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [161]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [166]:
print("Array B:\n")
print(B,"\n")
print("B.size:", B.size)
print("B.shape:", B.shape)
print("B.ndim:", B.ndim)

Array B:

[[ 0  1]
 [ 1  0]
 [ 1  1]
 [-1  0]] 

B.size: 8
B.shape: (4, 2)
B.ndim: 2


In [170]:
print("Array A:\n")
print(A,"\n")
print("Array B:\n")
print(B)

Array A:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Array B:

[[ 0  1]
 [ 1  0]
 [ 1  1]
 [-1  0]]


In [163]:
C = np.dot(A,B)
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [175]:
print("C.size:", C.size)
print("C.shape:", C.shape)
print("C.ndim:", C.ndim)

C.size: 6
C.shape: (3, 2)
C.ndim: 2


<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. So, please read and follow <a href="https://cognitiveclass.ai/blog/data-scientists-stand-out-by-sharing-your-notebooks/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01" target="_blank">this article</a> to learn how to share your work.
<hr>


## Author

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01" target="_blank">Joseph Santarcangelo</a>

## Other contributors

<a href="https://www.linkedin.com/in/jiahui-mavis-zhou-a4537814a?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Mavis Zhou</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                                          |
| ----------------- | ------- | ---------- | ----------------------------------------------------------- |
| 2021-01-05        | 2.2     | Malika     | Updated the solution for dot multiplication                 |
| 2020-09-09        | 2.1     | Malika     | Updated the screenshot for first two rows of the 3rd column |
| 2020-08-26        | 2.0     | Lavanya    | Moved lab to course repo in GitLab                          |
|                   |         |            |                                                             |
|                   |         |            |                                                             |

<hr/>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
